// LIST CONSTANTS
export const SET_LIST = 'SET_LIST';
export const INCREMENT_LIST = 'INCREMENT_LIST';
export const SET_LISTS = 'SET_LISTS';
export const LIST_REMOVE_ITEM = 'LIST_REMOVE_ITEM';
export const LIST_UPDATE_ITEMS = 'LIST_UPDATE_ITEMS';
export const DELETE_LIST = 'DELETE_LIST';
export const ADD_LIST_ITEM = 'ADD_LIST_ITEM';
export const REMOVE_LIST_ITEM = 'REMOVE_LIST_ITEM';
export const ADD_RECIPE_TO_LIST = 'ADD_RECIPE_TO_LIST';
export const CREATE_LIST = 'CREATE_LIST';

// SINGLE RECIPE
export const SET_SINGLE_RECIPE = 'SET_SINGLE_RECIPE';
export const DELETE_SINGLE_RECIPE = 'DELETE_SINGLE_RECIPE';
export const TOGGLE_LIKE = 'TOGGLE_LIKE';
export const TOGGLE_BOOKMARK = 'TOGGLE_BOOKMARK';
// GENERIC RECIPE LISTS
// POPULAR
export const SET_POPULAR_RECIPES = 'SET_POPULAR_RECIPES';
export const DELETE_POPULAR_RECIPES = 'DELETE_POPULAR_RECIPES';
// PAST LIKES
export const SET_LIKED_RECIPES = 'SET_LIKED_RECIPES';
export const DELETE_LIKED_RECIPES = 'DELETE_LIKED_RECIPES';
// BOOKMARKS
export const SET_BOOKMARKED_RECIPES = 'SET_BOOKMARKED_RECIPES';
// ALSO LIKED
export const SET_ALSO_LIKED_RECIPES = 'SET_ALSO_LIKED_RECIPES';

export const SET_INGREDIENTS = 'SET_INGREDIENTS';
export const CREATE_INGREDIENT = 'CREATE_INGREDIENT';
export const GET_ALL_RECIPES = 'GET_ALL_RECIPES';
export const SEARCHED_RECIPES = 'SEARCHED_RECIPES'
